services:
  mongo:
    image: mongo:latest
    container_name: ifccoin_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: ifccoin_backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data:
